# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/149/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/149/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/laravelk/repositories/mnsk_tests_1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/laravelk/repositories/mnsk_tests_1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/149/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/149/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/laravelk/repositories/mnsk_tests_1/CMakeFiles /home/laravelk/repositories/mnsk_tests_1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/laravelk/repositories/mnsk_tests_1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tprt

# Build rule for target.
tprt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tprt
.PHONY : tprt

# fast build rule for target.
tprt/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tprt.dir/build.make CMakeFiles/tprt.dir/build
.PHONY : tprt/fast

Horizon/FlatHorizon.o: Horizon/FlatHorizon.cpp.o

.PHONY : Horizon/FlatHorizon.o

# target to build an object file
Horizon/FlatHorizon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tprt.dir/build.make CMakeFiles/tprt.dir/Horizon/FlatHorizon.cpp.o
.PHONY : Horizon/FlatHorizon.cpp.o

Horizon/FlatHorizon.i: Horizon/FlatHorizon.cpp.i

.PHONY : Horizon/FlatHorizon.i

# target to preprocess a source file
Horizon/FlatHorizon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tprt.dir/build.make CMakeFiles/tprt.dir/Horizon/FlatHorizon.cpp.i
.PHONY : Horizon/FlatHorizon.cpp.i

Horizon/FlatHorizon.s: Horizon/FlatHorizon.cpp.s

.PHONY : Horizon/FlatHorizon.s

# target to generate assembly for a file
Horizon/FlatHorizon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tprt.dir/build.make CMakeFiles/tprt.dir/Horizon/FlatHorizon.cpp.s
.PHONY : Horizon/FlatHorizon.cpp.s

Horizon/GridHorizon.o: Horizon/GridHorizon.cpp.o

.PHONY : Horizon/GridHorizon.o

# target to build an object file
Horizon/GridHorizon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tprt.dir/build.make CMakeFiles/tprt.dir/Horizon/GridHorizon.cpp.o
.PHONY : Horizon/GridHorizon.cpp.o

Horizon/GridHorizon.i: Horizon/GridHorizon.cpp.i

.PHONY : Horizon/GridHorizon.i

# target to preprocess a source file
Horizon/GridHorizon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tprt.dir/build.make CMakeFiles/tprt.dir/Horizon/GridHorizon.cpp.i
.PHONY : Horizon/GridHorizon.cpp.i

Horizon/GridHorizon.s: Horizon/GridHorizon.cpp.s

.PHONY : Horizon/GridHorizon.s

# target to generate assembly for a file
Horizon/GridHorizon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tprt.dir/build.make CMakeFiles/tprt.dir/Horizon/GridHorizon.cpp.s
.PHONY : Horizon/GridHorizon.cpp.s

Layer.o: Layer.cpp.o

.PHONY : Layer.o

# target to build an object file
Layer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tprt.dir/build.make CMakeFiles/tprt.dir/Layer.cpp.o
.PHONY : Layer.cpp.o

Layer.i: Layer.cpp.i

.PHONY : Layer.i

# target to preprocess a source file
Layer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tprt.dir/build.make CMakeFiles/tprt.dir/Layer.cpp.i
.PHONY : Layer.cpp.i

Layer.s: Layer.cpp.s

.PHONY : Layer.s

# target to generate assembly for a file
Layer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tprt.dir/build.make CMakeFiles/tprt.dir/Layer.cpp.s
.PHONY : Layer.cpp.s

Math/Derivative.o: Math/Derivative.cpp.o

.PHONY : Math/Derivative.o

# target to build an object file
Math/Derivative.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tprt.dir/build.make CMakeFiles/tprt.dir/Math/Derivative.cpp.o
.PHONY : Math/Derivative.cpp.o

Math/Derivative.i: Math/Derivative.cpp.i

.PHONY : Math/Derivative.i

# target to preprocess a source file
Math/Derivative.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tprt.dir/build.make CMakeFiles/tprt.dir/Math/Derivative.cpp.i
.PHONY : Math/Derivative.cpp.i

Math/Derivative.s: Math/Derivative.cpp.s

.PHONY : Math/Derivative.s

# target to generate assembly for a file
Math/Derivative.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tprt.dir/build.make CMakeFiles/tprt.dir/Math/Derivative.cpp.s
.PHONY : Math/Derivative.cpp.s

Ray/Ray.o: Ray/Ray.cpp.o

.PHONY : Ray/Ray.o

# target to build an object file
Ray/Ray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tprt.dir/build.make CMakeFiles/tprt.dir/Ray/Ray.cpp.o
.PHONY : Ray/Ray.cpp.o

Ray/Ray.i: Ray/Ray.cpp.i

.PHONY : Ray/Ray.i

# target to preprocess a source file
Ray/Ray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tprt.dir/build.make CMakeFiles/tprt.dir/Ray/Ray.cpp.i
.PHONY : Ray/Ray.cpp.i

Ray/Ray.s: Ray/Ray.cpp.s

.PHONY : Ray/Ray.s

# target to generate assembly for a file
Ray/Ray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tprt.dir/build.make CMakeFiles/tprt.dir/Ray/Ray.cpp.s
.PHONY : Ray/Ray.cpp.s

Ray/RayData.o: Ray/RayData.cpp.o

.PHONY : Ray/RayData.o

# target to build an object file
Ray/RayData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tprt.dir/build.make CMakeFiles/tprt.dir/Ray/RayData.cpp.o
.PHONY : Ray/RayData.cpp.o

Ray/RayData.i: Ray/RayData.cpp.i

.PHONY : Ray/RayData.i

# target to preprocess a source file
Ray/RayData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tprt.dir/build.make CMakeFiles/tprt.dir/Ray/RayData.cpp.i
.PHONY : Ray/RayData.cpp.i

Ray/RayData.s: Ray/RayData.cpp.s

.PHONY : Ray/RayData.s

# target to generate assembly for a file
Ray/RayData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tprt.dir/build.make CMakeFiles/tprt.dir/Ray/RayData.cpp.s
.PHONY : Ray/RayData.cpp.s

Receiver.o: Receiver.cpp.o

.PHONY : Receiver.o

# target to build an object file
Receiver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tprt.dir/build.make CMakeFiles/tprt.dir/Receiver.cpp.o
.PHONY : Receiver.cpp.o

Receiver.i: Receiver.cpp.i

.PHONY : Receiver.i

# target to preprocess a source file
Receiver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tprt.dir/build.make CMakeFiles/tprt.dir/Receiver.cpp.i
.PHONY : Receiver.cpp.i

Receiver.s: Receiver.cpp.s

.PHONY : Receiver.s

# target to generate assembly for a file
Receiver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tprt.dir/build.make CMakeFiles/tprt.dir/Receiver.cpp.s
.PHONY : Receiver.cpp.s

Source.o: Source.cpp.o

.PHONY : Source.o

# target to build an object file
Source.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tprt.dir/build.make CMakeFiles/tprt.dir/Source.cpp.o
.PHONY : Source.cpp.o

Source.i: Source.cpp.i

.PHONY : Source.i

# target to preprocess a source file
Source.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tprt.dir/build.make CMakeFiles/tprt.dir/Source.cpp.i
.PHONY : Source.cpp.i

Source.s: Source.cpp.s

.PHONY : Source.s

# target to generate assembly for a file
Source.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tprt.dir/build.make CMakeFiles/tprt.dir/Source.cpp.s
.PHONY : Source.cpp.s

VelocityModel.o: VelocityModel.cpp.o

.PHONY : VelocityModel.o

# target to build an object file
VelocityModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tprt.dir/build.make CMakeFiles/tprt.dir/VelocityModel.cpp.o
.PHONY : VelocityModel.cpp.o

VelocityModel.i: VelocityModel.cpp.i

.PHONY : VelocityModel.i

# target to preprocess a source file
VelocityModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tprt.dir/build.make CMakeFiles/tprt.dir/VelocityModel.cpp.i
.PHONY : VelocityModel.cpp.i

VelocityModel.s: VelocityModel.cpp.s

.PHONY : VelocityModel.s

# target to generate assembly for a file
VelocityModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tprt.dir/build.make CMakeFiles/tprt.dir/VelocityModel.cpp.s
.PHONY : VelocityModel.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tprt.dir/build.make CMakeFiles/tprt.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tprt.dir/build.make CMakeFiles/tprt.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tprt.dir/build.make CMakeFiles/tprt.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tprt"
	@echo "... Horizon/FlatHorizon.o"
	@echo "... Horizon/FlatHorizon.i"
	@echo "... Horizon/FlatHorizon.s"
	@echo "... Horizon/GridHorizon.o"
	@echo "... Horizon/GridHorizon.i"
	@echo "... Horizon/GridHorizon.s"
	@echo "... Layer.o"
	@echo "... Layer.i"
	@echo "... Layer.s"
	@echo "... Math/Derivative.o"
	@echo "... Math/Derivative.i"
	@echo "... Math/Derivative.s"
	@echo "... Ray/Ray.o"
	@echo "... Ray/Ray.i"
	@echo "... Ray/Ray.s"
	@echo "... Ray/RayData.o"
	@echo "... Ray/RayData.i"
	@echo "... Ray/RayData.s"
	@echo "... Receiver.o"
	@echo "... Receiver.i"
	@echo "... Receiver.s"
	@echo "... Source.o"
	@echo "... Source.i"
	@echo "... Source.s"
	@echo "... VelocityModel.o"
	@echo "... VelocityModel.i"
	@echo "... VelocityModel.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

